# Inspired by this origin config file
# https://github.com/golangci/golangci-lint/blob/master/.golangci.yml

version: "2"
linters:
  default: none
  enable:
    - bodyclose
    - copyloopvar
    - depguard
    - dogsled
    - dupl
    - errcheck
    - funcorder
    - errorlint
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - mnd
    - nakedret
    - noctx
    - nolintlint
    - revive
    - staticcheck
    - testifylint
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    depguard:
      rules:
        main:
          allow:
            - $gostd
            - github.com/spf13/pflag
            - github.com/stretchr/testify
    dupl:
      threshold: 100
    funlen:
      lines: -1 # the number of lines (code + empty lines) is not a right metric and leads to code without empty line or one-liner.
      statements: 50
    goconst:
      min-len: 2
      min-occurrences: 3
    gocritic:
      disabled-checks:
        - dupImport # https://github.com/go-critic/go-critic/issues/845
        - ifElseChain
        - octalLiteral
        - whyNoLint
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gocyclo:
      min-complexity: 15
    lll:
      line-length: 140
    misspell:
      locale: US
    nolintlint:
      allow-unused: false # report any unused nolint directives
      require-explanation: false # don't require an explanation for nolint directives
      require-specific: false # don't require nolint directives to be specific about which linter is being skipped
    revive:
      rules:
        - name: unexported-return
          disabled: true
        - name: unused-parameter
    testifylint:
      disable:
        - require-error
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - goconst
          - gocritic
          - revive
        path: _test\.go
      - linters:
          - staticcheck
        text: "ST1003: type Api should be API"
      - linters:
          - staticcheck
        text: "ST1003: struct field Api should be API"
      - linters:
          - staticcheck
        text: "ST1003: func NewApi should be NewAPI"
      - linters:
          - staticcheck
        text: "ST1003: type HttpServer should be HTTPServer"
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - localmodule
    gofmt:
      simplify: false
    goimports:
      local-prefixes:
        - github.com/golangci/golangci-lint
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
