// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package fsops

import (
	"sync"
)

// Ensure, that WalkerMock does implement Walker.
// If this is not the case, regenerate this file with moq.
var _ Walker = &WalkerMock{}

// WalkerMock is a mock implementation of Walker.
//
//	func TestSomethingThatUsesWalker(t *testing.T) {
//
//		// make and configure a mocked Walker
//		mockedWalker := &WalkerMock{
//			WalkFunc: func(path string) ([]string, error) {
//				panic("mock out the Walk method")
//			},
//		}
//
//		// use mockedWalker in code that requires Walker
//		// and then make assertions.
//
//	}
type WalkerMock struct {
	// WalkFunc mocks the Walk method.
	WalkFunc func(path string) ([]string, error)

	// calls tracks calls to the methods.
	calls struct {
		// Walk holds details about calls to the Walk method.
		Walk []struct {
			// Path is the path argument value.
			Path string
		}
	}
	lockWalk sync.RWMutex
}

// Walk calls WalkFunc.
func (mock *WalkerMock) Walk(path string) ([]string, error) {
	if mock.WalkFunc == nil {
		panic("WalkerMock.WalkFunc: method is nil but Walker.Walk was just called")
	}
	callInfo := struct {
		Path string
	}{
		Path: path,
	}
	mock.lockWalk.Lock()
	mock.calls.Walk = append(mock.calls.Walk, callInfo)
	mock.lockWalk.Unlock()
	return mock.WalkFunc(path)
}

// WalkCalls gets all the calls that were made to Walk.
// Check the length with:
//
//	len(mockedWalker.WalkCalls())
func (mock *WalkerMock) WalkCalls() []struct {
	Path string
} {
	var calls []struct {
		Path string
	}
	mock.lockWalk.RLock()
	calls = mock.calls.Walk
	mock.lockWalk.RUnlock()
	return calls
}
